trigger:
  branches:
    include:
      - main
      - feature/*

pool: group_agent_pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'group_sc'
    backendAzureRmResourceGroupName: 'sagar'
    backendAzureRmStorageAccountName: '420420'
    backendAzureRmContainerName: 'gautam'
    backendAzureRmKey: 'ravindra.tf'


- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

     - 
- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'group_sc'

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'group_sc'